version: '3.8'

services:
  backend:
    container_name: taskapi_backend
    build:
      context: ./TaskApi  # Points to the folder containing the Dockerfile
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    ports:
      - "5000:5000"
    environment:
      - JwtSettings__Secret=YourVeryStrongSecretKeyWithAtLeast32Characters!
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=taskdb;Username=taskuser;Password=taskpassword;SSL Mode=Disable
    volumes:
      - ./TaskApi:/app  # Optional: Mounts local files for live development
    restart: always
    depends_on:
      - database
    command: ["/bin/sh", "-c", "dotnet ef database update && dotnet run"]

  frontend:
    image: node:18 # Use official Node.js image
    container_name: taskapi_frontend
    working_dir: /app
    volumes:
      - ./task-frontend:/app # Mount frontend code
    ports:
      - "5173:5173" # Vue Vite default port
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    depends_on:
      - backend

  database:
    image: postgres:15
    container_name: taskapi_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "taskuser", "-d", "taskdb"]
      interval: 15s
      retries: 5
      start_period: 20s

volumes:
  db_data:
